# Copyright 2026 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""RESULTS.md and JUnit XML, in the same shape the dev-VM gate produces."""

from __future__ import annotations

import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

from .config import Config
from .core import ScenarioResult


def write_results_md(results: list[ScenarioResult], config: Config, path: Path) -> None:
    overall = "PASSED" if all(r.ok or r.skipped_reason for r in results) else "FAILED"
    # A dry run must never produce a file that reads like evidence: it builds
    # nothing and asserts nothing, so a plain "PASSED" here would be a claim
    # about infrastructure that was never touched.
    if config.dry_run:
        lines = [
            f"## NKP dev E2E results: {overall} (DRY RUN - nothing was created or asserted)",
            "",
            "> This is a dry run. The scenarios were planned and every command was",
            "> printed, but no cluster was built and no assertion was evaluated.",
            "> Do not attach this as test evidence.",
            "",
            f"- **Date:** {datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}",
            "- **Mode:** `--dry-run`",
        ]
    else:
        lines = [
            f"## NKP dev E2E results: {overall}",
            "",
            f"- **Date:** {datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}",
        ]
    for label, value in config.describe():
        lines.append(f"- **{label}:** `{value}`")
    lines += [
        "",
        "| Scenario | Result | Duration | Topology |",
        "|---|---|---|---|",
    ]
    icon = {"PASS": "✅ PASS", "FAIL": "❌ FAIL", "SKIP": "⏭️ SKIP"}
    for r in results:
        mins = f"{r.seconds / 60:.1f} min"
        broken = [p for p in r.phases if p.name in ("cleanup", "collect") and not p.ok]
        flag = f" ⚠ {', '.join(p.name for p in broken)} failed" if broken else ""
        lines.append(f"| {r.name} | {icon[r.status]}{flag} | {mins} | {getattr(r, 'topology', '')} |")

    leftovers = [(r, p) for r in results for p in r.phases
                 if p.name in ("cleanup", "collect") and not p.ok]
    if leftovers:
        lines += ["", "**Cleanup or collect failed** - the verdict stands, the lab may not be clean:", ""]
        for r, p in leftovers:
            lines.append(f"- **{r.name}** {p.name}: {p.error}")
    failures = [r for r in results if not r.ok and not r.skipped_reason]
    if failures:
        lines += ["", "<details><summary>Failure detail</summary>", ""]
        for r in failures:
            lines.append(f"- **{r.name}** — {r.error}")
        lines += ["", "</details>"]

    lines += [
        "",
        "_Generated by hack/dev-e2e/run_e2e.py; per-scenario logs and diagnostics "
        "are in this directory._",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def write_junit(results: list[ScenarioResult], path: Path) -> None:
    suite = ET.Element(
        "testsuite",
        name="nkp-dev-e2e",
        tests=str(len(results)),
        failures=str(sum(1 for r in results if not r.ok and not r.skipped_reason)),
        skipped=str(sum(1 for r in results if r.skipped_reason)),
        time=f"{sum(r.seconds for r in results):.1f}",
    )
    for r in results:
        case = ET.SubElement(
            suite, "testcase", classname="nkp.dev.e2e", name=r.name, time=f"{r.seconds:.1f}"
        )
        if r.skipped_reason:
            ET.SubElement(case, "skipped", message=r.skipped_reason)
        elif not r.ok:
            failure = ET.SubElement(case, "failure", message=r.error[:200])
            failure.text = "\n".join(
                f"{p.name}: {'ok' if p.ok else 'FAILED ' + p.error}" for p in r.phases
            )
    ET.ElementTree(suite).write(path, encoding="utf-8", xml_declaration=True)
